### ISSUE TITLE
kannski er það gott mál

### ISSUE THREAD

**Issue by 4wl** [ThnksCJ/RusherCrack#1]
Endilega póstaðu meira

**Comment by ThnksCJ** [comment]
Hvað viltu að ég setji inn? ég er með rusher-sprungu og hvata, ég gæti líka sent inn uppruna (ekki byggjanlegur) hvata 1.9.11

Því miður er íslenska ekki fyrsta tungumálið mitt svo ég er ekki frábær í því

**Comment by 4wl** [comment]
ok sendu hvata 1.9.11 sem er flott

**Comment by ThnksCJ** [comment]
Ég fæ það til þín eins fljótt og auðið er, þarf samt að gera eitthvað í því

**Comment by 4wl** [comment]
allt í lagi
